config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :books
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, :author, :price, :published, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end

    def new
        @book = Book.new
    end

    def create
        title = params[:book][:title]
        author = params[:book][:author]
        price = params[:book][:price]
        # date
        published = params[:book][:published]
        begin
            @book = Book.new(
                title: title,
                author: author,
                price: price,
                published: published
            )
            if @book.save
                redirect_to books_path, notice: "Book created successfully."
            else
                render :new
            end
        rescue
            render :new
        end
    end
def edit
    @book = Book.find(params[:id])
end

def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
        redirect_to books_path, notice: "Book updated successfully."
    else
        render :edit
    end
end

def show
    @book = Book.find(params[:id])
end

def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "Book deleted successfully."
end

private

def book_params
    params.require(:book).permit(
        :title,
        :author,
        :price,
        :published
    )
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/destroy.html.erb
# Desroy Book Page
<%= stylesheet_link_tag 'books' %>

<div class="books_header">
  <h1>Delete Book</h1>
</div>

<div class="button_main_bar">
    <div class="button_nav">
        <%= link_to 'Back', books_path %>
    </div>
</div>

<div class="delete_book">
    <h2>Are you sure you want to delete this book?</h2>
    <h2><%= @book.title %></h2>
    <%= form_with(model: @book, local: true) do |form| %>
        <div class="actions">
            <%= form.submit 'Delete' %>
        </div>
    <% end %>
</div>

<ul>
    <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
</ul>
</div>

app/views/books/edit.html.erb
<%= stylesheet_link_tag 'books' %>

<div class="books_header">
    <h1>Edit Book</h1>
</div>

<div class="button_main_bar">
    <div class="button_nav">
        <%= link_to 'Back', books_path %>
    </div>
</div>

<div class="edit_book">
    <h2>Enter Book Details</h2>
    <%= form_with(model: @book, local:true) do |form| %>
        <div class="field">
            <%= form.label :title %><br>
            <%= form.text_field :title %>
        </div>

        <div class="field">
            <%= form.label :author %><br>
            <%= form.text_field :author %>
        </div>

        <div class="field">
            <%= form.label :price %><br>
            <%= form.text_field :price %>
        </div>

        <div class="field">
            <%= form.label :published %><br>
            <%= form.date_field :published %>
        </div>

        <div class="actions">
            <%= form.submit %>
        </div>

        <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>

    <% end %>
</div>

app/views/books/index.html.erb
<%= stylesheet_link_tag 'books' %>

<div class="books_header">
  <h1>Book List</h1>
</div>

<div class="button_main_bar">
    <div class="button_nav">
        <%= link_to 'Add New Book', new_book_path %>
    </div>
</div>

<div class="books_list">
    <table>
        <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Price</th>
            <th>Published</th>
            <th></th>
            <th>Actions</th>
            <th colspan="3"></th>
        </tr>
        </thead>

    
        <tbody>
        <% @books.each do |book| %>
            <tr>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.price %></td>
            <td><%= book.published %></td>
            <td><%= link_to 'Show', book %></td>
            <td><%= link_to 'Edit', edit_book_path(book) %></td>
            <td><%= button_to "Delete", book, method: :delete, data: { turbo_confirm: 'Are you absolutely sure about deleting this precious book?' } %></td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/books/new.html.erb
<%= stylesheet_link_tag 'books' %>

<div class="books_header">
    <h1>Add New Book</h1>
</div>

<div class="button_main_bar">
    <div class="button_nav">
        <%= link_to 'Back', books_path %>
    </div>
</div>

<div class="add_book">
    <h2>Enter Book Details</h2>
    <%= form_with(model: @book, local:true) do |form| %>
        <div class="field">
            <%= form.label :title %><br>
            <%= form.text_field :title %>
        </div>

        <div class="field">
            <%= form.label :author %><br>
            <%= form.text_field :author %>
        </div>

        <div class="field">
            <%= form.label :price %><br>
            <%= form.text_field :price %>
        </div>
        
        <div class="field">
            <%= form.label :published %><br>
            <%= form.date_field :published %>
        </div>


        <div class="actions">
            <%= form.submit %>
        </div>

        <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>

    <% end %>
</div>

app/views/books/show.html.erb
<%= stylesheet_link_tag 'books' %>

<div class="books_header">
    <h1>Book Details</h1>
</div>

<div class="button_main_bar">
    <div class="button_nav">
        <%= link_to 'Back', books_path %>
    </div>
</div>

<div class="book_details">
    <h2>Selected Book</h2>
    <span class="book_title"><%= @book.title %></span>
    <span class="book_title"><%= @book.author %></span>
    <span class="book_title"><%= @book.price %></span>
    <span class="book_title"><%= @book.published %></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CSCE 431 Book Collection 1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p id="alert"><%= alert %></p>
    <% end %>

    <%= javascript_include_tag "turbo", type: "module" %>
    <%= yield(:javascript) %>
  </body>
</html>